### PR TITLE
change UI of website

### PR DESCRIPTION
**Pull request by abitsalihu**
I changed the `User Interface` of the website by making it more modern and minimalistic.

Below are the images of how the website will look in `Desktop view` and `Mobile view`: 

I deleted and renewed a lot of the css so it is cleaner and more readable for when you want to change something!

`Desktop view :`

Screen Shot 2022-10-06 at 19 12 19

`Mobile view :`

Screen Shot 2022-10-06 at 19 16 12

`SUCCESS validation :`

Screen Shot 2022-10-06 at 19 18 25

`FAILED validation :`

Screen Shot 2022-10-06 at 19 18 33

`HOVER on footer icon :`

Screen Shot 2022-10-06 at 19 18 13

### CODE REVIEW

**Comment by kuspia** [comment]
looks neat and clean, can u please add a navbar section and create sections for https://github.com/kuspia/Card-Validator/issues/2 this issue 

I want you to add sections and make it look like a website, rest in issue 2 those sections can be completed further 


One thing is that I am looking for a dynamic or gamified type of UI, please add something extra or innovative before I merge this PR

**Comment by abitsalihu** [comment]
@kuspia Yeah sure I'll add the `navbar`, and can I play around with `vanilla JS` maybe I can come up with something more interesting.

Does `more gamified` mean that the UI should push more towards gaming?

**Comment by kuspia** [comment]
ok u can fix #9 issue and in PR mention it as closed after u are done so that it get closed,

gamified means something cool and innovative u might have seen an interesting web-site already.

**Comment by abitsalihu** [comment]
@kuspia, Alright I'll try and see what I can come up with. :)

**Comment by abitsalihu** [comment]
New UI that fixes issue #2  and issue #9 , also added a feature to change the background of the website when the information is correct or wrong!

And added a new font for credit card input and title!

`Dekstop view:`

https://user-images.githubusercontent.com/94648837/194404709-d7d0255d-ac66-4c08-9501-1b84b86586c3.mov

`Mobile view:`


https://user-images.githubusercontent.com/94648837/194404758-66aad4ea-52d5-4102-92be-cc74f9480534.mov

**Comment by abitsalihu** [comment]
@kuspia will do, thank you. :)

**Comment by kuspia** [comment]
@abitsalihu I merged and saw this on Heroku after deploying

image


So request you to deploy on your end if everything works fine create a new PR, I am marking this as invalid as it doesn't reflect over the Heroku app after merging

**Pull request merged**
